In [673]:
import pandas as pd                                    
import numpy as np  
import matplotlib.pyplot as plt
from numpy import linalg as LA

In [674]:
df = pd.read_csv('CrowdstormingDataJuly1st.csv')

# Visualization of Data

In [675]:
df.ix[:13, :13]

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

,playerShort,player,club,leagueCountry,birthday,height,weight,position,games,victories,ties,defeats,goals
0,lucas-wilchez,Lucas Wilchez,Real Zaragoza,Spain,31.08.1983,177.0,72.0,Attacking Midfielder,1,0,0,1,0
1,john-utaka,John Utaka,Montpellier HSC,France,08.01.1982,179.0,82.0,Right Winger,1,0,0,1,0
2,abdon-prats,Abdón Prats,RCD Mallorca,Spain,17.12.1992,181.0,79.0,NaN,1,0,1,0,0
3,pablo-mari,Pablo Marí,RCD Mallorca,Spain,31.08.1993,191.0,87.0,Center Back,1,1,0,0,0
4,ruben-pena,Rubén Peña,Real Valladolid,Spain,18.07.1991,172.0,70.0,Right Midfielder,1,1,0,0,0
5,aaron-hughes,Aaron Hughes,Fulham FC,England,08.11.1979,182.0,71.0,Center Back,1,0,0,1,0
6,aleksandar-kolarov,Aleksandar Kolarov,Manchester City,England,10.11.1985,187.0,80.0,Left Fullback,1,1,0,0,0
7,alexander-tettey,Alexander Tettey,Norwich City,England,04.04.1986,180.0,68.0,Defensive Midfielder,1,0,0,1,0
8,anders-lindegaard,Anders Lindegaard,Manchester United,England,13.04.1984,193.0,80.0,Goalkeeper,1,0,1,0,0
9,andreas-beck,Andreas Beck,1899 Hoffenheim,Germany,13.03.1987,180.0,70.0,Right Fullback,1,1,0,0,0
10,antonio-rukavina,Antonio Rukavina,Real Valladolid,Spain,26.01.1984,177.0,74.0,Right Fullback,2,2,0,0,0
11,ashkan-dejagah,Ashkan Dejagah,Fulham FC,England,05.07.1986,181.0,74.0,Left Winger,1,1,0,0,0
12,benedikt-hoewedes,Benedikt Höwedes,FC Schalke 04,Germany,29.02.1988,187.0,80.0,Center Back,1,1,0,0,0
13,chris-baird,Chris Baird,Fulham FC,England,25.02.1982,186.0,77.0,Defensive Midfielder,1,0,0,1,0

In [676]:
df.ix[:13, 13:27]

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

,yellowCards,yellowReds,redCards,photoID,rater1,rater2,refNum,refCountry,Alpha_3,meanIAT,nIAT,seIAT,meanExp,nExp
0,0,0,0,95212.jpg,0.25,0.50,1,1,GRC,0.326391,712.0,0.000564,0.396000,750.0
1,1,0,0,1663.jpg,0.75,0.75,2,2,ZMB,0.203375,40.0,0.010875,-0.204082,49.0
2,1,0,0,NaN,NaN,NaN,3,3,ESP,0.369894,1785.0,0.000229,0.588297,1897.0
3,0,0,0,NaN,NaN,NaN,3,3,ESP,0.369894,1785.0,0.000229,0.588297,1897.0
4,0,0,0,NaN,NaN,NaN,3,3,ESP,0.369894,1785.0,0.000229,0.588297,1897.0
5,0,0,0,3868.jpg,0.25,0.00,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
6,0,0,0,47704.jpg,0.00,0.25,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
7,0,0,0,22356.jpg,1.00,1.00,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
8,0,0,0,16528.jpg,0.25,0.25,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
9,0,0,0,36499.jpg,0.00,0.00,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
10,1,0,0,59786.jpg,0.00,0.00,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
11,0,0,0,23229.jpg,0.50,0.50,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
12,0,0,0,59387.jpg,0.00,0.00,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0
13,0,0,0,8252.jpg,0.00,0.00,4,4,LUX,0.325185,127.0,0.003297,0.538462,130.0

Which features are irrelevant?

# Drop some features

In [677]:
df = df.drop(["player","playerShort","club","Alpha_3","photoID","nIAT","seIAT","nExp","seExp","goals"],axis=1)
#"victories", "ties", "defeats"

It's mostly clear why the features above are irrelevant. Maybe the club can have a decision in the decisions, maybe they are correct when they say: Varcerlona or Real Vardrid. The Standard errors are not relevant if not used connected to the mean value.

In [678]:
df = df.dropna()

# BMI

Player names are not that relevant

In [679]:
height = df["height"].to_numpy()/100
weight= df["weight"].to_numpy()
BMI = weight/(height**2)
df = df.drop(["height", "weight"] , axis = 1)
df['BMI'] = BMI

# Raters

In [680]:
df = df[df["rater2"]==df["rater1"]]
df = df.drop(["rater2"],axis=1)

In [681]:
rating = df["rater1"].to_numpy()
df= df.drop(["rater1"], axis = 1)
df["rating"] = rating

# Birthday

In [682]:
birthday = df["birthday"].to_numpy()

In [683]:
birthday[-2:]

array(['04.10.1980', '10.10.1991'], dtype=object)

We assume that the age is not relevant

# League Country

In [684]:
df['leagueCountry'].value_counts(sort=True)

Germany    29720
England    24048
Spain      21367
France     13230
Name: leagueCountry, dtype: int64

In [685]:
leagueCountry = df["leagueCountry"].to_numpy()

In [686]:
league_one_hot_Germany = np.where(leagueCountry == 'Germany', 1, 0)
league_one_hot_Spain = np.where(leagueCountry == 'Spain', 1, 0)
league_one_hot_France = np.where(leagueCountry == 'France', 1, 0)
league_one_hot_England = np.where(leagueCountry == 'England', 1, 0)

In [687]:
league_one_hot = np.stack((league_one_hot_Germany, league_one_hot_Spain, league_one_hot_France, league_one_hot_England), axis = -1)

In [688]:
df_Germany = df[df["leagueCountry"]=='Germany']

We assume that the league is also not important, more important is the country of the referee, and it's effect can be seen in the meanIAT

# Player position

In [689]:
df['position'].value_counts(sort=True)

Center Back             16374
Center Forward          12845
Defensive Midfielder    10822
Goalkeeper               8103
Attacking Midfielder     7703
Left Fullback            6668
Right Fullback           6344
Left Midfielder          4316
Center Midfielder        4025
Right Midfielder         3946
Left Winger              3863
Right Winger             3356
Name: position, dtype: int64

We also assume that the player position is not relevant

# Referee

In [690]:
df['refNum'].value_counts(sort=True)

3099    594
88      552
933     552
756     547
1214    511
       ...
882       1
2446      1
2995      1
2914      1
1441      1
Name: refNum, Length: 2736, dtype: int64

We just use the meanIAT as a relevant value for the referee

# Games

The players who play less games usually are substitutes and they play less time

In [691]:
df = df[df["games"]>10]
df_lie = df[df["games"]<10] # For exercise 2.4

# Cards

In [566]:
df['games'].value_counts(sort=True)

1     44453
2     14335
3      7752
4      4947
5      3583
6      2680
7      2048
8      1651
9      1355
10     1120
11      831
12      669
13      561
14      442
15      348
16      306
17      222
18      207
19      152
20      111
21      109
22       86
23       78
24       65
25       59
26       40
27       26
28       25
29       19
30       18
32       13
31       12
34        8
33        7
37        6
35        5
41        4
36        3
40        3
44        1
42        1
46        1
39        1
38        1
47        1
Name: games, dtype: int64

In [568]:
df['redCards'].value_counts(sort=True)

0    4182
1     251
2       8
Name: redCards, dtype: int64

In [569]:
df['yellowReds'].value_counts(sort=True)

0    4221
1     213
2       6
3       1
Name: yellowReds, dtype: int64

In [570]:
df['yellowCards'].value_counts(sort=True)

1     1147
0      918
2      915
3      618
4      403
5      229
6      107
7       62
8       20
9       12
10       7
11       1
14       1
13       1
Name: yellowCards, dtype: int64

We want to see the skin color bias for cards in general

In [571]:
def label_maker(df):  
    weight_yellow = 0.5
    weight_yellow_red = 0.75
    weight_red = 1

    yellow = df['yellowCards'].to_numpy()
    yellow_red = df['yellowReds'].to_numpy()
    red = df['redCards'].to_numpy()

    cards = weight_yellow * yellow + weight_yellow_red* yellow_red + weight_red* red

    games = df['games'].to_numpy()

    label = cards/games

    mean_label = np.mean(label, axis=0)
    label_centralized = np.subtract(label,mean_label)
    return label, label_centralized, mean_label

In [572]:
label , label_centralized, mean_label = label_maker(df)
label_DE , label_centralized_DE, mean_label_DE= label_maker(df[df["leagueCountry"]=='Germany'])

# Victories

In [573]:
#victories = df['victories'].to_numpy()
#ties = df['ties'].to_numpy()
#defeats = df['defeats'].to_numpy()

Maybe leaving this features uncombined is the best way to go, otherwise there would be a bias defining the weights of each one.

# Preparing data for analysis

In [577]:
df.ix[:,:13]

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

,leagueCountry,birthday,position,games,victories,ties,defeats,yellowCards,yellowReds,redCards,refNum,refCountry,meanIAT
1181,France,01.08.1980,Left Fullback,11,7,0,4,4,0,0,66,4,0.325185
1249,France,20.08.1981,Right Fullback,12,2,6,4,2,0,0,67,7,0.334684
1357,France,10.07.1976,Right Winger,11,4,3,4,1,0,0,67,7,0.334684
1533,England,12.04.1982,Center Back,11,4,1,6,2,0,0,70,45,0.326690
1928,Spain,09.09.1987,Defensive Midfielder,11,6,3,2,3,0,0,77,44,0.326690
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145101,Germany,05.04.1979,Goalkeeper,28,15,7,6,1,0,0,3099,8,0.336628
145103,Germany,22.11.1986,Right Fullback,11,3,3,5,3,0,0,3099,8,0.336628
145110,Germany,13.01.1988,Defensive Midfielder,12,5,3,4,1,0,0,3099,8,0.336628
145122,Germany,06.08.1984,Center Forward,16,5,4,7,3,0,0,3099,8,0.336628
145648,France,02.11.1980,Center Back,11,8,1,2,5,0,0,3127,15,0.354707

In [580]:
def features_maker(df):
    df_drop = df.drop(["leagueCountry","birthday","position","games","yellowCards", "yellowReds", "redCards", "refCountry", "refNum"],axis=1)
    features = df_drop.to_numpy()
    mean = np.mean(features, axis=0)

    features_centralized = np.subtract(features, mean)
    return features, features_centralized

In [581]:
features, features_centralized = features_maker(df)
features_DE, features_centralized_DE = features_maker(df[df["leagueCountry"]=='Germany'])

# 2.2 Model Creation

In [582]:
def Linear_Regression(features, label):   # Data must be centralized
    S = np.dot(features.T, features)
    Z = np.dot(features.T, label)
    S_inverse = LA.inv(S)
    beta = np.dot(S_inverse, Z)
    Y = np.dot(features, beta)
    return Y

In [583]:
Y = Linear_Regression(features_centralized, label_centralized)
Y = Y + mean_label
yerr = Y- label
print("Error: ", np.mean(yerr**2))

Error:  0.0037468577991980724

In [625]:
def cross_validation_LR_error(features, label):
    N_SPLITS = 5
    N_REPEATS = 5
    N_TREES = 3
    N_MIN = 20

    err = []
    rkf = RepeatedKFold(n_splits=N_SPLITS, n_repeats=N_REPEATS)
    count = 1
    for train_index, test_index in rkf.split(features):
        print(count, "/",  N_SPLITS*N_REPEATS)
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = features[train_index], features[test_index]
        y_train, y_test = label[train_index], label[test_index]
        Y = Linear_Regression(features, label)
        Y = Y + mean_label
        yerr = Y- label
        err.append(np.nansum(yerr**2)/len(yerr))
        count+=1
    return np.nansum(err)/(len(err))

In [637]:
error_LR_original = cross_validation_LR_error(features_centralized, label_centralized)

1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25

In [638]:
error_LR_original

0.009178670172170705

# With SVD

In [584]:
# Data must be centralized
u, s, vh = LA.svd(features_centralized, full_matrices= False)

x = np.dot(u.T, label_centralized)

z = np.dot(LA.inv(np.diag(s)), x)

beta2 = np.dot(vh, z)

Y2 = np.dot(features_centralized, beta2)
Y2 = Y2 + mean_label

yerr2 = Y2- label
print("Error: ", np.mean(yerr2**2))

Error:  0.02502991060769771

# Regression forrest

In [585]:
class Node:
    pass

class Tree:
    def __init__(self):
        self.root = Node()
    
    def find_leaf(self, x):
        node = self.root
        while hasattr(node, "feature"):
            j = node.feature
            if x[j] <= node.threshold:
                node = node.left
            else:
                node = node.right
        return node

In [611]:
class RegressionTree(Tree):  
    def __init__(self):
        super(RegressionTree, self).__init__()
        
    def train(self, data, labels, n_min=20):
        '''
        data: the feature matrix for all digits
        labels: the corresponding ground-truth responses
        n_min: termination criterion (don't split if a node contains fewer instances)
        '''
        N, D = data.shape
        D_try = int(np.sqrt(D)) # how many features to consider for each split Regression

        # initialize the root node
        self.root.data = data
        self.root.labels = labels
        
        #put root in stack
        stack = [self.root]
        while len(stack):
            node = stack.pop()
            n = node.data.shape[0] # number of instances in present node
            if n >= n_min:
                # Call 'make_Regression_split_node()' with 'D_try' randomly selected 
                # feature indices. This turns 'node' into a split node
                # and returns the two children, which must be placed on the 'stack'.
                
                perm = np.random.permutation(D)   # permute D indices
                left, right = make_Regression_split_node(node, perm[:D_try]) #select :D_try of permuted indices
                                                       #for 'make_Regression_split_node()'
                # put children in stack
                stack.append(left)
                stack.append(right)
            else:
                # Call 'make_Regression_leaf_node()' to turn 'node' into a leaf node.
                make_Regression_leaf_node(node)
                
    def predict(self, x):
        leaf = self.find_leaf(x)
        # compute p(y | x)
        return leaf.response

In [612]:
def make_Regression_split_node(node, feature_indices):
    '''
    node: the node to be split
    feature_indices: a numpy array of length 'D_try', containing the feature 
                     indices to be considered in the present split
    '''
    n, D = node.data.shape

    # find best feature j (among 'feature_indices') and best threshold t for the split
    e_min = 1e100
    j_min, t_min = 0, 0
    for j in feature_indices:
        # remove duplicate features
        dj = np.sort(np.unique(node.data[:,j]))
        # compute candidate thresholds in the middle between consecutive feature values
        tj = 0.5 * (dj[1:] + dj[:-1]) 
        # each candidate threshold we need to compute Gini impurities of the resulting children node
        for t in tj:
            left_indices = np.where(node.data[:,j] <= t)
            nl = len(left_indices)
            ll = node.labels[left_indices]
            mean_ll = np.mean(ll)
            el = np.sum((ll-mean_ll)**2)
            right_indices = np.where(node.data[:,j] > t)
            nr = len(right_indices)
            lr = node.labels[right_indices]
            mean_lr = np.mean(lr)
            er = np.sum((lr-mean_lr)**2)
            # choose the the best threshold that minimizes sum of Gini impurities
            if el + er < e_min:
                e_min = el + er
                j_min = j
                t_min = t

    # create children
    left = Node()
    right = Node()
    
    # initialize 'left' and 'right' with the data subsets and labels
    # according to the optimal split found above
    left.data = node.data[node.data[:,j_min] <= t_min, :]
    left.labels = node.labels[node.data[:,j_min] <= t_min]
    right.data = node.data[node.data[:,j_min] > t_min, :]
    right.labels = node.labels[node.data[:,j_min] > t_min]

    # turn the current 'node' into a split node
    # (store children and split condition)
    node.left = left
    node.right = right
    node.feature = j_min
    node.threshold = t_min

    # return the children (to be placed on the stack)
    return left, right

In [613]:
def make_Regression_leaf_node(node):
    '''
    node: the node to become a leaf
    '''
    node.N = node.labels.shape[0]
    node.response = np.sum(node.labels)/node.N

In [614]:
class RegressionForest():
    def __init__(self, n_trees):
        # create ensemble
        self.trees = [RegressionTree() for i in range(n_trees)]
    
    def train(self, data, labels, n_min=0):
        for tree in self.trees:
            # train each tree, using a bootstrap sample of the data
            bootstrap = np.random.choice(len(data), size=len(data))
            tree.train(data[bootstrap], labels[bootstrap], n_min)

    def predict(self, x):
        # compute the ensemble prediction
        mean = np.mean([tree.predict(x) for tree in self.trees])
        return mean

In [615]:
#n_min = 20
#DF = RegressionForest(40)

In [616]:
#DF.train(features_DE, label_DE, n_min)

In [617]:
#def Y(x):    
    #return DF.predict(x)

In [618]:
#Y_predicted = np.zeros(len(features_DE))
#for i in range(len(features_DE)):
#    Y_predicted[i] = Y(features_DE[i,:])
#Y_abweichung = Y_predicted - label_DE
#result = np.nansum(Y_abweichung**2)/len(Y_abweichung)

In [619]:
#print(result)

In [620]:
from sklearn.model_selection import RepeatedKFold

In [621]:
def cross_validation_RF_error(features, label):
    N_SPLITS = 5
    N_REPEATS = 5
    N_TREES = 3
    N_MIN = 20

    err = []
    rkf = RepeatedKFold(n_splits=N_SPLITS, n_repeats=N_REPEATS)
    count = 1
    for train_index, test_index in rkf.split(features):
        print(count, "/",  N_SPLITS*N_REPEATS)
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = features[train_index], features[test_index]
        y_train, y_test = label[train_index], label[test_index]
        rgf = RegressionForest(N_TREES)
        rgf.train(X_train, y_train, n_min)

        Ypredict = [0]*len(y_test)
        for i in range(len(y_test)):
            Ypredict[i] = rgf.predict(X_test[i, ::])

        Yerr = Ypredict - y_test
        err.append(np.nansum(Yerr**2)/len(Yerr))
        count+=1
    return np.nansum(err)/(len(err))

In [639]:
error_RF_original = cross_validation_RF_error(features, label)
print('Error: ' , error_RF_original)

1 / 25

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars

2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Error:  0.0037967276642440124

In [538]:
rating_perms = np.array([np.random.permutation(df.rating.tolist()) for i in range(19)])

In [634]:
error_RF_array = []
error_LR_array = []
for i in range(19):
    df_no_rater = df.drop(["rating"], axis = 1)
    print("perm", i+1)
    df_no_rater["rating"] = rating_perms[i]
    features_new, features_centralized_new = features_maker(df_no_rater)
    print("Regression Forrest")
    error_RF = cross_validation_RF_error(features_new, label)
    print("Linear Regression")
    error_LR = cross_validation_LR_error(features_centralized_new, label_centralized)
    error_RF_array.append(error_RF)
    error_LR_array.append(error_LR)

perm 1
Regression Forrest
1 / 25

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars

2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 2
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 3
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 4
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 5
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 6
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 7
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 8
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 9
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 10
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 11
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 12
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 13
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 14
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 15
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 16
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 17
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 18
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
perm 19
Regression Forrest
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25
Linear Regression
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
16 / 25
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
25 / 25

In [635]:
error_RF_array

[0.003987268665313739,
 0.004004550766474222,
 0.003972698186762758,
 0.003947643226024447,
 0.004037249134816959,
 0.004007648452985813,
 0.004023726842680797,
 0.004011852652686712,
 0.004008733812982041,
 0.004012295868576522,
 0.004020122226852944,
 0.003961558661986811,
 0.004025204740991037,
 0.0039945914931204555,
 0.004006086488773376,
 0.004028288755479908,
 0.004000856053224486,
 0.004013905317037759,
 0.003992338630420954]

In [636]:
error_LR_array

[0.009178700893841282,
 0.009175537778699108,
 0.009178694425700209,
 0.00917891306696518,
 0.009175687622945444,
 0.009179036712391639,
 0.009178042142390213,
 0.009179211495929884,
 0.009178737696294459,
 0.009178468573260885,
 0.00917915007017209,
 0.009177361132918217,
 0.00917876622548369,
 0.009179197472921136,
 0.00917609357986927,
 0.00917917765913647,
 0.009178805273135674,
 0.009179109393139522,
 0.009177092195761339]

### Comparison

In [640]:
comparison_LR = error_LR_array - error_LR_original

In [641]:
comparison_RF=error_RF_array - error_RF_original

In [631]:
error_RF_array

[0.004013344891205505]

In [633]:
error_LR_array

[0.009178700893841282]

In [645]:
higher_test_error_LR = np.sum(np.where(comparison_LR, 1 ,0))

In [646]:
higher_test_error_RF = np.sum(np.where(comparison_RF, 1 ,0))

In [649]:
print("From 19 random Permutations the following number of datasets exhibit a higher test error \n using linear regresion: " , higher_test_error_LR)
print("\n")
print("From 19 random Permutations the following number of datasets exhibit a higher test error \n using a regression forrest: " , higher_test_error_RF)

From 19 random Permutations the following number of datasets exhibit a higher test error
 using linear regresion:  19


From 19 random Permutations the following number of datasets exhibit a higher test error
 using a regression forrest:  19

We can therefore conclude that there is a skin color bias in the card decisions

In [670]:
df_dark = df[df["rating"]>0.5]
df_light = df[df["rating"]<0.5]

In [671]:
label_dark, l1, m1 = label_maker(df_dark)
label_light, l1, m1 = label_maker(df_light)

In [672]:
if np.mean(label_dark)> np.mean(label_light):
    print("Dark colored players tend to get more cards")
else:
    print("Light colored players tend to get more cards")

Light colored players tend to get more cards

# 2.4 How to lie with statistics

In [694]:
features_lie, features_lie_centralized = features_maker(df_lie) 
label_lie, label_lie_centralized, mean_label_lie = label_maker(df_lie)

In [ ]:
rating_perms_lie = np.array([np.random.permutation(df_lie.rating.tolist()) for i in range(19)])
error_RF_array = []
error_LR_array = []
for i in range(3):
    df_no_rater = df_lie.drop(["rating"], axis = 1)
    print("perm", i+1)
    df_no_rater["rating"] = rating_perms_lie[i]
    features_new, features_centralized_new = features_maker(df_no_rater)
    print("Regression Forrest")
    error_RF = cross_validation_RF_error(features_new, label_lie)
    print("Linear Regression")
    error_LR = cross_validation_LR_error(features_centralized_new, label_lie_centralized)
    error_RF_array.append(error_RF)
    error_LR_array.append(error_LR)

perm 1
Regression Forrest
1 / 25

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars

# 2.5 Alternate Hypotesis

Maybe the dark colored players tend to have a higher BMI, and therefore they are more robust and their tackles can be seen more hard than it is

In [654]:
df_lie = pd.read_csv('CrowdstormingDataJuly1st.csv')
df_lie = df_lie.drop(["player","playerShort","club","Alpha_3","photoID","nIAT","seIAT","nExp","seExp","goals"],axis=1)
df_lie = df_lie.dropna()

C:\Users\timoc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [leagueCountry, birthday, position, games, victories, ties, defeats, yellowCards, yellowReds, redCards, refNum, refCountry, meanIAT]
Index: []